# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GBIFServices
                                 A QGIS plugin
 Use the GBIF API to get all species occurence point records within a polygon layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-06
        copyright            : (C) 2025 by Aidan O'Brien
        email                : aidan.w.obrien@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GBIFServices class from file GBIFServices.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gbif_services import GBIFServices
    return GBIFServices(iface)
